import os
gettext = lambda s: s
DATA_DIR = os.path.dirname(os.path.dirname(__file__))
"""
Django settings for brighttours2 project.

Generated by 'django-admin startproject' using Django 1.8.17.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'f^(i(%5^47$9r-^cn&lyq7sbu*vjt_-pid1!7wc813@3efcz45'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['160.153.225.99', 'localhost']
ADMINS = [('Nejdet Dogru', 'nejdet.dogru@ibu.edu.ba')]

# Application definition





ROOT_URLCONF = 'brighttours2.urls'



WSGI_APPLICATION = 'brighttours2.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases




# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'Europe/Sarajevo'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(DATA_DIR, 'media')
STATIC_ROOT = os.path.join(DATA_DIR, 'static')

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'brighttours2', 'static'),
)
SITE_ID = 1



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'brighttours2', 'templates'),],
        'OPTIONS': {
            'context_processors': [
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.media',
                'django.template.context_processors.csrf',
                'django.template.context_processors.tz',
                'sekizai.context_processors.sekizai',
                'django.template.context_processors.static',
                'cms.context_processors.cms_settings',
            ],
            'loaders': [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
                'django.template.loaders.eggs.Loader',
            ],
        },
    },
]


MIDDLEWARE_CLASSES = (
    'cms.middleware.utils.ApphookReloadMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'cms.middleware.user.CurrentUserMiddleware',
    'cms.middleware.page.CurrentPageMiddleware',
    'cms.middleware.toolbar.ToolbarMiddleware',
    'cms.middleware.language.LanguageCookieMiddleware'
)

INSTALLED_APPS = (
    'djangocms_admin_style',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.admin',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'django.contrib.staticfiles',
    'django.contrib.messages',
    'cms',
    'menus',
    'sekizai',
    'treebeard',
    'djangocms_text_ckeditor',
    'filer',
    'easy_thumbnails',
    'djangocms_column',
    'djangocms_link',
    'cmsplugin_filer_file',
    'cmsplugin_filer_folder',
    'cmsplugin_filer_image',
    'cmsplugin_filer_utils',
    'djangocms_style',
    'djangocms_snippet',
    'djangocms_googlemap',
    'djangocms_video',
    'brighttours2',
    'adminsortable',
    'cmsplugin_contact_plus',
    'djangocms_forms'

)

LANGUAGES = (
    ## Customize this
    ('en', gettext('en')),
)

CMS_LANGUAGES = {
    ## Customize this
    1: [
        {
            'code': 'en',
            'name': gettext('en'),
            'redirect_on_fallback': True,
            'public': True,
            'hide_untranslated': False,
        },
    ],
    'default': {
        'redirect_on_fallback': True,
        'public': True,
        'hide_untranslated': False,
    },
}


CMS_TEMPLATES = (
    ## Customize this
    ('homeen.html', 'Home En'),
    ('homeen2.html', 'Home En2'),
    ('bosniatours.html', 'Bosnia Tours'),
    ('balkantours.html', 'Balkan Tours'),
    ('cities.html', 'Cities'),
    ('cities2.html', 'Cities2'),
    ('rentacar.html', 'Rent-a-Car'),
    ('alternatives.html', 'Alternatives'),
    ('contact.html', 'Contact'),
    ('bosniatours2.html', 'Bosnia Tours2'),
    ('sarajevotour.html', "Sarajevo Tour"),
    ('sm-tour.html', "SM Tour"),
    ('smt-tour.html', "SMT Tour"),
    ('smts-tour.html', "SMTS Tour"),
    ('smjs-tour.html', "SMJS Tour"),
    ('smvt-tour.html', "SMVT Tour"),
    ('albania1-tour.html', "ALBANIA1 Tour"),
    ('albania2-tour.html', "ALBANIA2 Tour"),
    ('bk-tour.html', "BK Tour"),
    ('bs-tour.html', "BS Tour"),
    ('bkkm-tour.html', "BKKM Tour"),
    ('hk-tour.html', "HK Tour"),
    ('km-tour.html', "KM Tour"),
    ('bb-tour.html', "BB Tour"),
    ('gallery.html', "Gallery"),
    ('aboutus.html', 'aboutus'),
    ('hotels.html', 'Hotels'),
    ('dailytours.html', 'DailyTours')
)

CMS_PERMISSION = True

CMS_PLACEHOLDER_CONF = {}

DATABASES = {
    'default': {
        'CONN_MAX_AGE': 0,
        'ENGINE': 'django.db.backends.sqlite3',
        'HOST': 'localhost',
        'NAME': 'project.db',
        'PASSWORD': '',
        'PORT': '',
        'USER': ''
    }
}

MIGRATION_MODULES = {
    
}

THUMBNAIL_PROCESSORS = (
    'easy_thumbnails.processors.colorspace',
    'easy_thumbnails.processors.autocrop',
    'filer.thumbnail_processors.scale_and_crop_with_subject_location',
    'easy_thumbnails.processors.filters'
)

CMSPLUGIN_CONTACT_PLUS_TEMPLATES = [
    ('cmsplugin_contact_plus/contact.html', 'Contact Form'),
    ('cmsplugin_contact_plus/contact2.html', 'Contact2 Form')
]


CONTACT_PLUS_FROM_EMAIL='brighttourscontactform@gmail.com'
CONTACT_PLUS_REPLY_EMAIL_LABEL='brighttourscontactform@gmail.com'

EMAIL_BACKEND ='django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST_USER = 'brighttourscontactform@gmail.com'
EMAIL_HOST_PASSWORD = '@Bright387'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST='smtp.gmail.com'


DJANGOCMS_FORMS_PLUGIN_MODULE = gettext('Generic')
DJANGOCMS_FORMS_PLUGIN_NAME = gettext('Form')
DJANGOCMS_FORMS_DEFAULT_TEMPLATE = 'djangocms_forms/form_template/default.html'
DJANGOCMS_FORMS_TEMPLATES = (
    ('djangocms_forms/form_template/default.html', gettext('Default')),
)
DJANGOCMS_FORMS_USE_HTML5_REQUIRED = False
DJANGOCMS_FORMS_WIDGET_CSS_CLASSES = {'__all__': ('form-control', ) }
DJANGOCMS_FORMS_REDIRECT_DELAY = 1000  # 1 seconds

